spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_project
    username: root
    password: root

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: 9bkWy1uOck7vFY4Xtajb44JevZl9Gzuwqc0759U36RpdPYHZJPUIvgXEar0ue9ax